<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <Company>PureFusion</Company>
    <Product>PureFusionIRC</Product>
    <Authors>PureFusionIRC contributors</Authors>
    <Copyright>Copyright (c) PureFusionIRC contributors</Copyright>
    <Version>0.1.0</Version>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>
</Project>
